plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// 회원가입 & 로그인 위해 추가
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	// spring-security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	// JJWT 라이브러리 (JWT 구현체) 3종 세트
	implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.2' // 인터페이스 정의
	runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-impl', version: '0.11.2' // 실제 구현체
	runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.11.2' // JSON 변환기 (Claims ↔ JSON 직렬화용)

	// 이메일 인증
	implementation 'org.springframework.boot:spring-boot-starter-mail'

	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'
	// 최신 Twilio Core SDK
	implementation 'com.twilio.sdk:twilio:10.7.2'

	// Websocket
	implementation 'org.springframework.boot:spring-boot-starter-websocket'

	// Tomcat - websocket 모듈 의존성 추가
	implementation 'org.apache.tomcat.embed:tomcat-embed-websocket'


	//Google Gloud Speech
	implementation 'com.google.cloud:google-cloud-speech:4.39.0'

	//Json Parsing
	implementation 'org.json:json:20231013'

	// Springdoc OpenAPI UI
	implementation 'org.springdoc:springdoc-openapi-ui:1.6.11'

	// Swagger annotations
	implementation 'io.swagger.core.v3:swagger-annotations:2.2.10'
}

tasks.named('test') {
	useJUnitPlatform()
}
